# Generated by Django 2.2.2 on 2020-01-12 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelstryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='authors',
            field=models.ManyToManyField(null=True, to='modelstryapp.Author'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modelstryapp.Blog'),
        ),
    ]
