# Generated by Django 2.2.2 on 2020-01-14 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelstryapp', '0002_auto_20200111_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeBlog',
            fields=[
                ('blog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='modelstryapp.Blog')),
                ('theme', models.CharField(max_length=200)),
            ],
            bases=('modelstryapp.blog',),
        ),
        migrations.AlterField(
            model_name='entry',
            name='authors',
            field=models.ManyToManyField(blank=True, to='modelstryapp.Author'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelstryapp.Blog'),
        ),
    ]
